name: Deploy to Production
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Sync files to remote server
              uses: appleboy/rsync-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT || '22' }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: "./"
                  target: /home/${{ secrets.SSH_USERNAME }}/app
                  delete: false

            - name: SSH and deploy
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT || '22' }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      set -e 
                      cd /home/${{ secrets.SSH_USERNAME }}/app
                      docker volume create caddy_data || true
                      docker volume create n8n_data || true 
                      docker compose pull || true 
                      docker compose up -d --remove-orphans 
                      docker image prune -f 
                      docker compose ps
